name: Publish

on:
  release:
    types:
      - published

jobs:
  publish:
    name: Publish NuGet packages
    runs-on: ubuntu-latest
    steps:
      - name: Pull code
        uses: actions/checkout@v3
      - name: Use .NET
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json
      - name: Push packages
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run:
          set -xe

          source_directory=src
          release_directory=releases

          pack_flags="--configuration Release  --output '$release_directory' /p:ContinuousIntegrationBuild=true"

          dotnet pack $pack_flags "$source_directory\\Chr.Avro"
          dotnet pack $pack_flags "$source_directory\\Chr.Avro.Binary"
          dotnet pack $pack_flags "$source_directory\\Chr.Avro.Cli"
          dotnet pack $pack_flags "$source_directory\\Chr.Avro.Codegen"
          dotnet pack $pack_flags "$source_directory\\Chr.Avro.Confluent"
          dotnet pack $pack_flags "$source_directory\\Chr.Avro.Json"

          push_flags_publish="--api-key '$NUGET_API_KEY' --skip-duplicate --source tetragon-nuget"

          dotnet nuget push push_flags_publish "$release_directory/*.nupkg"
          dotnet nuget push push_flags_publish "$release_directory/*.snupkg"
        shell: bash
